using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AADTest1.Models
{
    /// <summary>
    /// Represents user token cache for the user. Generated by VS template.
    /// </summary>
    public class UserTokenCache
    {
        [Key]
        public int UserTokenCacheId { get; set; }

        [StringLength(255)]
        [Index]
        [Required]
        public string WebUserUniqueId { get; set; }
        public byte[] CacheBits { get; set; }
        public DateTime LastWrite { get; set; }
    }
}